title: Hacker hacker s
description: 'https://github.com/settings/pages_verified_domains/new'
template:
  repo: hacker-hacker-s-template
  name: hacker-hacker-s
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
